### ISSUE TITLE
Exit policy order

### ISSUE THREAD

**Issue by dmgawel** [NullHypothesis/zoossh#3]
Parsing exit policy as it is now does not preserve accept/reject order which is necessary to properly evalute if node could be used as exit node (according to Tor spec: https://gitweb.torproject.org/torspec.git/tree/dir-spec.txt#n474).

**Comment by NullHypothesis** [comment]
Yes, I can see that this is a clear shortcoming. Unfortunately, I don't have plans to develop zoossh further because I only needed it as fundament for [sybilhunter](https://github.com/NullHypothesis/sybilhunter). I will leave this open and if anyone wants to write a patch, I would be happy to merge it.

**Comment by dmgawel** [comment]
Resolved by #9.
